### PR TITLE
Removed CMFDefault dependency

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by gforcada** [comment]
And tests running here: http://jenkins.plone.org/job/pull-request/118

**Comment by gforcada** [comment]
There's a few packages left to do: http://jenkins.plone.org/view/Dependencies/job/plone-package-dependencies-cmf/lastSuccessfulBuild/artifact/deps/Products.CMFDefault.txt :)

**Comment by gforcada** [comment]
I added the package to autocheckouts: https://github.com/plone/buildout.coredev/commit/c49b70bfbe48d3f510f60d8c8e94f31533e8ed12

**Comment by tomgross** [comment]
Interesting CMFPlone and Archetypes are not picked up. They are merged already.
See https://github.com/plone/plone.app.content/pull/29

**Comment by tomgross** [comment]
And https://github.com/plone/plone.app.testing/pull/13

**Pull request merged**
