### PR TITLE
Paste delete rename default page

### PR DESCRIPTION
**Pull request by gotcha**
When a default object is used as layout for a container,
- if the default object is deleted or moved with cut and paste, reset the default_page property of the container.
- if the default object is renamed (iow id is changed), fix the default_page property of the container.

### CODE REVIEW

**Comment by tisto** [comment]
@gotcha you forgot to add the package to auto-checkout. Your changes are not tested by jenkins.

**Comment by gotcha** [comment]
Nope, I am currently running alltests locally.

**Comment by tisto** [comment]
@gotcha you just made a release of a package that breaks 39 of our 92 robot tests: 

http://jenkins.plone.org/job/plone-5.0-python-2.7-robot/

I told you that your changes break the build and you made a release anyways. We are a sprint and you are  blocking everybody from working. In addition we currently can't update our jenkins configuration, because the build is broken. This is not acceptable.

**Comment by gotcha** [comment]
I understand I am the cause of troubles.
However, how should I have known that running alltests does not run all tests...

**Comment by tisto** [comment]
Fair point. "--all" is not mentioned here: https://buildoutcoredev.readthedocs.org/en/latest/intro.html

Will add a section later today. 

Though, you have to check the jenkins status or the testbot mail after your commits to make sure they do not break anything. Even if you run "alltests --all" and "alltests-at --all" locally, it is still possible that something breaks on jenkins.

**Comment by gotcha** [comment]
I did check. What am I supposed to do when I find out it is broken ?
Outside debugging it to fix it ?

**Comment by tisto** [comment]
Why did you make a release when you checked and saw that the build is broken?

First thing I usually do when I break the build is to revert my commit to not block other people and to verify that my changes are really responsible for the regression.

See our CI rules for details: http://buildoutcoredev.readthedocs.org/en/latest/continous-integration.html

Sometimes there are failures on Jenkins that people can not reproduce. If you can prove with a revert that your commit is not responsible, I will fix that problem for you. If your commit is responsible and you can not reproduce the problem, I can try to help with it. Though, you have to work against Jenkins then. We have a Jenkins job that allows you to test a pull requests (or branch) before merging:

http://jenkins.plone.org/view/All/job/pull-request

**Comment by gotcha** [comment]
Cause I did not know I needed to run three different commands to run all tests.

Is there an explanation somewhere of the process for http://jenkins.plone.org/view/All/job/pull-request ?

I reverted my change and robot-tests remains broken. Breakage is unrelated to inclusion of CMFDynamicViewFTI release.

I feel shouted at. Which I do not like. And will only lead to me contributing less.

**Pull request merged**
